# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-28 20:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Biblioteca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biblioteca', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('autor', models.CharField(max_length=100)),
                ('editorial', models.CharField(blank=True, max_length=100, null=True)),
                ('edicion', models.CharField(blank=True, max_length=20, null=True)),
                ('publicacion', models.IntegerField(blank=True, null=True, verbose_name='Año de publicacion')),
                ('resumen', models.TextField(blank=True, null=True)),
                ('paginas', models.IntegerField(blank=True, null=True, verbose_name='Cantidad de Páginas')),
                ('observacion', models.TextField(blank=True, null=True)),
                ('cantidad', models.IntegerField()),
                ('fecha_ingreso', models.DateTimeField(help_text='Fecha de ingreso a Biblioteca', verbose_name='Fecha de Ingreso')),
                ('isbn', models.CharField(blank=True, help_text='International Standard Book Number', max_length=25, null=True, verbose_name='ISBN')),
                ('dewey', models.CharField(max_length=20, null=True)),
                ('malaga', models.CharField(max_length=20, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='uploads/tapa', verbose_name='Tapa de Libro')),
                ('libro_digital', models.FileField(blank=True, help_text='Opcion para colocar el libro digital al sistema', null=True, upload_to='uploads/libros', verbose_name='Libro digital')),
                ('biblioteca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteca.Biblioteca')),
            ],
        ),
    ]
